language: java
jdk:
- openjdk8
script: 

addons:
  sonarcloud:
    organization: "vincenzovisconti16"
    token:
      secure: f8e24e8a3e972dfc95dd00aea7646f54a2f6555e

script:
  - ant build
  - sonar-scanner
